env:
  contexts:
    - name: juice-shop
      urls:
        - http://localhost:3000
      includePaths:
        - "http://localhost:3000.*"
      excludePaths:
        - ".*\\.png"
        - ".*\\.jpg"
        - ".*\\.svg"
        - ".*\\.woff2?"
      authentication:
        method: json
        parameters:
          loginPageUrl: http://localhost:3000/#/login
          loginRequestUrl: http://localhost:3000/rest/user/login
          loginRequestBody: '{"email":"{%username%}","password":"{%password%}"}'
        verification:
          method: response
          loggedInRegex: '"authentication"'
          loggedOutRegex: '"error"'
      sessionManagement:
        method: cookie
      users:
        - name: student
          credentials:
            username: student@juice-sh.op
            password: Student!23
  parameters:
    failOnError: true
    progressToStdout: true

jobs:
  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 10
  - type: spider
    parameters:
      context: juice-shop
      user: student
      maxDuration: 3
  - type: spiderAjax
    parameters:
      context: juice-shop
      user: student
      maxDuration: 5
  - type: passiveScan-wait
    parameters:
      maxDuration: 5
  - type: activeScan
    parameters:
      context: juice-shop
      user: student
      maxRuleDurationInMins: 3
      maxScanDurationInMins: 30
  - type: report
    parameters:
      template: traditional-xml
      reportDir: /zap/wrk
      reportFile: juice-shop.af